// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcoV2WJyNoZpNyMr-XZIpUScD8Jte69O0',
    appId: '1:931077496114:web:886b43376f96532fd30b2b',
    messagingSenderId: '931077496114',
    projectId: 'memory-care-64711',
    authDomain: 'memory-care-64711.firebaseapp.com',
    storageBucket: 'memory-care-64711.firebasestorage.app',
    measurementId: 'G-TTF43JWZNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4dBP33z_0-azkt3SQEMK5nEJ84ZLi-SA',
    appId: '1:931077496114:android:6507387dd3f42c6ed30b2b',
    messagingSenderId: '931077496114',
    projectId: 'memory-care-64711',
    storageBucket: 'memory-care-64711.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxBXzPRWzNJ-H3yLhnMKBYhOIKMebIhWQ',
    appId: '1:931077496114:ios:603430c041225386d30b2b',
    messagingSenderId: '931077496114',
    projectId: 'memory-care-64711',
    storageBucket: 'memory-care-64711.firebasestorage.app',
    iosBundleId: 'com.example.memorycare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxBXzPRWzNJ-H3yLhnMKBYhOIKMebIhWQ',
    appId: '1:931077496114:ios:603430c041225386d30b2b',
    messagingSenderId: '931077496114',
    projectId: 'memory-care-64711',
    storageBucket: 'memory-care-64711.firebasestorage.app',
    iosBundleId: 'com.example.memorycare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcoV2WJyNoZpNyMr-XZIpUScD8Jte69O0',
    appId: '1:931077496114:web:8dd39b161a5689b1d30b2b',
    messagingSenderId: '931077496114',
    projectId: 'memory-care-64711',
    authDomain: 'memory-care-64711.firebaseapp.com',
    storageBucket: 'memory-care-64711.firebasestorage.app',
    measurementId: 'G-5NP6QZ8YK4',
  );

}